# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-22 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_item_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data',
            field=models.CharField(max_length=30),
        ),
    ]
